# SIP to gRPC Gateway Configuration

# Network Settings
bind_ip=0.0.0.0

# Feature Flags
# If true, echo audio back and do NOT send to gRPC.
# If false, do NOT echo audio and DO send to gRPC.
echo_only=true

# SIP Settings
sip_port=5060

# gRPC Settings
grpc_port=50051

# RTP Settings
rtp_min_port=10000
rtp_max_port=20000
